describe('My First Test', () => {
  it('Visits the initial project page', () => {
    cy.visit('/')
    cy.contains('List of foods:')
  })
  it('Add food to the list')
  cy.visit('/')
    cy.get('[formControlName="food.id"]').type('1')
    cy.get('[formControlName="food.name"]').type('apple')
    cy.get('[formControlName="food.description"]').type('juicy')
    cy.get('[formControlName="food.color"]').type('red')
    cy.get('[formControlName="food.group"]').type('fruit')
    cy.get('button').click()
    cy.contains('apple')
    it('Delete food to the list')
    cy.visit('/')
    cy.get('[id="food-list"]').contains('This isnt a real food').click()
      cy.should('not.include','apple')
})
